### ISSUE TITLE
List of bug reports 09 19 2016

### ISSUE THREAD

**Issue by Darkrifts** [amanuel2/OS_Mirror#1]
1) Mouse leaves "shadows" behind still
2) It is possible to delete the green text at the start of command lines under some circumstances

**Comment by amanuel2** [comment]
Mouse leaves shadow when you press enter and Click :/
The green text? Thats the normal shell .. Boner | Linux Shell

**Comment by Darkrifts** [comment]
Well, the shell's green text can be deleted and replaced with other text (keeping the green color)

**Comment by amanuel2** [comment]
And what do you want it to be replaced to?

**Comment by amanuel2** [comment]
Normal Shell : https://i.ytimg.com/vi/iJq7656jjps/maxresdefault.jpg

**Comment by amanuel2** [comment]
Mouse Issue Solved.. Now what do you want the green text to be exactly? This is the normal shell green text.. Search Up .. "Command Shell" , and look up the images.

**Comment by amanuel2** [comment]
Ok are you still folowing this issue? (5 days)

**Comment by amanuel2** [comment]
This issue seems resolved. Therefore closed. Please refer to this OS , this os dev tutorial has been discontinued ! https://github.com/Bone-Project/BoneOS
