### ISSUE TITLE
Indentation is FUGLY

### ISSUE THREAD

**Issue by benhj** [amanuel2/OS_Mirror#2]
Sorry to say but its really quite horrible to behold. If you're unsure how to properly indent, I'm sure there's a free tool that could do it for you!

**Comment by amanuel2** [comment]
@benhj I Would Love to see the free tool! Sorry for my indentation im truely sorry! Me and Partners , Are making BoneOS Here: https://github.com/Bone-Project/BoneOS .. Feel free to make issues there , i will be making the first Real Update today . Thanks!!! :smile:

**Comment by benhj** [comment]
Check out this article: https://blog.codinghorror.com/the-broken-window-theory/

Good luck with the operating system, its a very ambitious endeavor and one in which I'm sure you'll be sure to learn a lot along the way! :-)

**Comment by amanuel2** [comment]
Thanks a lot @benhj will sure , hope you can support me along the way 😉
